apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: haproxy
    app.kubernetes.io/component: haproxy
    app.kubernetes.io/instance: haproxy
  name: haproxy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: haproxy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: haproxy
    spec:
      containers:
      - image: docker.io/haproxy
        imagePullPolicy: IfNotPresent
        name: haproxy
        ports:
        - containerPort: 2887
          hostPort: 2887
          protocol: TCP
        - containerPort: 3887
          hostPort: 3887
          protocol: TCP
        - containerPort: 2888
          hostPort: 2888
          protocol: TCP
        - containerPort: 3888
          hostPort: 3888
          protocol: TCP
        - containerPort: 2889
          hostPort: 2889
          protocol: TCP
        - containerPort: 3889
          hostPort: 3889
          protocol: TCP
        - containerPort: 2181
          hostPort: 2181
          protocol: TCP
        - containerPort: 2182
          hostPort: 2182
          protocol: TCP
        - containerPort: 2183
          hostPort: 2183
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          name: haproxycfg
          subPath: haproxy.cfg
      dnsPolicy: ClusterFirst
      #nodeName: ip-10-0-128-219.ap-southeast-1.compute.internal
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: haproxy
      serviceAccountName: haproxy
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: haproxycfg
        name: haproxycfg

